# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('code', models.CharField(max_length=4, serialize=False, primary_key=True, db_column='B_ID')),
                ('b_d', models.CharField(max_length=1, null=True, db_column='B_D', blank=True)),
                ('b_uid', models.IntegerField(null=True, db_column='B_UID', blank=True)),
                ('last_name', models.CharField(max_length=18, null=True, db_column='B_Last_Name', blank=True)),
                ('b_last_name_grk', models.CharField(max_length=18, null=True, db_column='B_Last_Name_Grk', blank=True)),
                ('first_name', models.CharField(max_length=28, null=True, db_column='B_First_Name', blank=True)),
                ('b_first_name_grk', models.CharField(max_length=18, null=True, db_column='B_First_Name_Grk', blank=True)),
                ('middle_name', models.CharField(max_length=18, null=True, db_column='B_Middle_Name', blank=True)),
                ('b_suffix_name', models.CharField(max_length=5, null=True, db_column='B_Suffix_Name', blank=True)),
                ('b_middle_name_grk', models.CharField(max_length=18, null=True, db_column='B_Middle_Name_Grk', blank=True)),
                ('b_father_name', models.CharField(max_length=18, null=True, db_column='B_Father_Name', blank=True)),
                ('b_father_name_grk', models.CharField(max_length=18, null=True, db_column='B_Father_Name_Grk', blank=True)),
                ('b_mother_name', models.CharField(max_length=18, null=True, db_column='B_Mother_Name', blank=True)),
                ('b_mother_name_grk', models.CharField(max_length=18, null=True, db_column='B_Mother_Name_Grk', blank=True)),
                ('country', models.CharField(max_length=2, null=True, db_column='B_CN_KEY', blank=True)),
                ('status', models.CharField(max_length=1, null=True, verbose_name='Status', db_column='B_Bio_Status', blank=True)),
                ('b_available', models.DateField(null=True, db_column='B_Available', blank=True)),
                ('rank', models.CharField(max_length=4, null=True, verbose_name='Rank', db_column='B_Position_1st', blank=True)),
                ('b_ex_crew', models.CharField(max_length=1, null=True, db_column='B_Ex_Crew', blank=True)),
                ('b_rank1_r_key', models.CharField(max_length=4, null=True, db_column='B_Rank1_R_KEY', blank=True)),
                ('b_type1_vt_key', models.CharField(max_length=4, null=True, db_column='B_Type1_VT_KEY', blank=True)),
                ('b_rank2_r_key', models.CharField(max_length=4, null=True, db_column='B_Rank2_R_KEY', blank=True)),
                ('b_type2_vt_key', models.CharField(max_length=4, null=True, db_column='B_Type2_VT_KEY', blank=True)),
                ('b_birth_date', models.DateField(null=True, db_column='B_Birth_Date', blank=True)),
                ('b_birth_place', models.CharField(max_length=32, null=True, db_column='B_Birth_Place', blank=True)),
                ('b_height', models.CharField(max_length=5, null=True, db_column='B_Height', blank=True)),
                ('b_weight', models.CharField(max_length=5, null=True, db_column='B_Weight', blank=True)),
                ('b_bmi', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='B_BMI', blank=True)),
                ('b_phone_1', models.CharField(max_length=16, null=True, db_column='B_Phone_1', blank=True)),
                ('b_phone_2', models.CharField(max_length=16, null=True, db_column='B_Phone_2', blank=True)),
                ('b_metro_addr_1', models.CharField(max_length=32, null=True, db_column='B_Metro_Addr_1', blank=True)),
                ('b_metro_addr_2', models.CharField(max_length=32, null=True, db_column='B_Metro_Addr_2', blank=True)),
                ('b_metro_addr_3', models.CharField(max_length=32, null=True, db_column='B_Metro_Addr_3', blank=True)),
                ('b_metro_addr_4', models.CharField(max_length=32, null=True, db_column='B_Metro_Addr_4', blank=True)),
                ('b_prov_addr_1', models.CharField(max_length=16, null=True, db_column='B_Prov_Addr_1', blank=True)),
                ('b_prov_addr_2', models.CharField(max_length=16, null=True, db_column='B_Prov_Addr_2', blank=True)),
                ('b_prov_addr_3', models.CharField(max_length=16, null=True, db_column='B_Prov_Addr_3', blank=True)),
                ('b_prov_addr_4', models.CharField(max_length=16, null=True, db_column='B_Prov_Addr_4', blank=True)),
                ('b_addr_grk_1', models.CharField(max_length=16, null=True, db_column='B_Addr_Grk_1', blank=True)),
                ('b_addr_grk_2', models.CharField(max_length=16, null=True, db_column='B_Addr_Grk_2', blank=True)),
                ('b_addr_grk_3', models.CharField(max_length=16, null=True, db_column='B_Addr_Grk_3', blank=True)),
                ('b_addr_grk_4', models.CharField(max_length=16, null=True, db_column='B_Addr_Grk_4', blank=True)),
                ('b_marital_status', models.CharField(max_length=1, null=True, db_column='B_Marital_Status', blank=True)),
                ('b_number_dependents', models.IntegerField(null=True, db_column='B_Number_Dependents', blank=True)),
                ('b_emergency_name', models.CharField(max_length=24, null=True, db_column='B_Emergency_Name', blank=True)),
                ('b_emergency_relation', models.CharField(max_length=4, null=True, db_column='B_Emergency_Relation', blank=True)),
                ('b_emergency_phone', models.CharField(max_length=16, null=True, db_column='B_Emergency_Phone', blank=True)),
                ('b_emergency_addr_1', models.CharField(max_length=32, null=True, db_column='B_Emergency_Addr_1', blank=True)),
                ('b_emergency_addr_2', models.CharField(max_length=32, null=True, db_column='B_Emergency_Addr_2', blank=True)),
                ('b_emergency_addr_3', models.CharField(max_length=32, null=True, db_column='B_Emergency_Addr_3', blank=True)),
                ('b_emergency_addr_4', models.CharField(max_length=32, null=True, db_column='B_Emergency_Addr_4', blank=True)),
                ('b_educ_note_1', models.CharField(max_length=34, null=True, db_column='B_Educ_Note_1', blank=True)),
                ('b_educ_note_2', models.CharField(max_length=34, null=True, db_column='B_Educ_Note_2', blank=True)),
                ('b_mother_language', models.CharField(max_length=8, null=True, db_column='B_Mother_Language', blank=True)),
                ('b_english', models.CharField(max_length=1, null=True, db_column='B_English', blank=True)),
                ('b_comments', models.CharField(max_length=60, null=True, db_column='B_Comments', blank=True)),
                ('b_wife_name', models.CharField(max_length=34, null=True, db_column='B_Wife_Name', blank=True)),
                ('b_wife_birthdate', models.DateField(null=True, db_column='B_Wife_BirthDate', blank=True)),
                ('b_wife_job', models.CharField(max_length=1, null=True, db_column='B_Wife_Job', blank=True)),
                ('b_tax_status', models.CharField(max_length=1, null=True, db_column='B_Tax_Status', blank=True)),
                ('b_tax_acct', models.CharField(max_length=20, null=True, db_column='B_Tax_Acct', blank=True)),
                ('b_tax_office', models.CharField(max_length=30, null=True, db_column='B_Tax_Office', blank=True)),
                ('b_sss', models.CharField(max_length=16, null=True, db_column='B_SSS', blank=True)),
                ('b_phealth', models.CharField(max_length=16, null=True, db_column='B_PHealth', blank=True)),
                ('b_vocational', models.CharField(max_length=16, null=True, db_column='B_Vocational', blank=True)),
                ('b_hs_grad', models.CharField(max_length=1, null=True, db_column='B_HS_Grad', blank=True)),
                ('b_hs_date', models.DateField(null=True, db_column='B_HS_Date', blank=True)),
                ('b_nautical_school', models.CharField(max_length=16, null=True, db_column='B_Nautical_School', blank=True)),
                ('b_nautical_degree', models.CharField(max_length=4, null=True, db_column='B_Nautical_Degree', blank=True)),
                ('b_nautical_date', models.DateField(null=True, db_column='B_Nautical_Date', blank=True)),
                ('b_other_school', models.CharField(max_length=16, null=True, db_column='B_Other_School', blank=True)),
                ('b_other_degree', models.CharField(max_length=8, null=True, db_column='B_Other_Degree', blank=True)),
                ('b_other_date', models.DateField(null=True, db_column='B_Other_Date', blank=True)),
                ('b_union', models.CharField(max_length=1, null=True, db_column='B_Union', blank=True)),
                ('b_separation_type', models.CharField(max_length=1, null=True, db_column='B_Separation_Type', blank=True)),
                ('b_sea_months', models.IntegerField(null=True, db_column='B_Sea_Months', blank=True)),
                ('b_high_rank1_r_key', models.CharField(max_length=4, null=True, db_column='B_High_Rank1_R_KEY', blank=True)),
                ('b_vtype_rank1_vt_key', models.CharField(max_length=4, null=True, db_column='B_VType_Rank1_VT_KEY', blank=True)),
                ('b_high_rank2_r_key', models.CharField(max_length=4, null=True, db_column='B_High_Rank2_R_KEY', blank=True)),
                ('b_vtype_rank2_vt_key', models.CharField(max_length=4, null=True, db_column='B_VType_Rank2_VT_KEY', blank=True)),
                ('b_skills', models.CharField(max_length=32, null=True, db_column='B_Skills', blank=True)),
                ('b_nick_name', models.CharField(max_length=12, null=True, db_column='B_Nick_Name', blank=True)),
                ('b_email_address', models.CharField(max_length=45, null=True, db_column='B_Email_Address', blank=True)),
                ('b_ofw_id', models.CharField(max_length=32, null=True, db_column='B_OFW_ID', blank=True)),
                ('b_pagibig', models.CharField(max_length=16, null=True, db_column='B_Pagibig', blank=True)),
                ('b_freemail', models.CharField(max_length=1, null=True, db_column='B_Freemail', blank=True)),
                ('b_time_last', models.TimeField(null=True, db_column='B_Time_Last', blank=True)),
                ('b_who_last', models.CharField(max_length=4, null=True, db_column='B_Who_Last', blank=True)),
            ],
            options={
                'db_table': 'bio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('c_d', models.CharField(max_length=1, null=True, db_column='C_D', blank=True)),
                ('certificate', models.CharField(max_length=4, serialize=False, primary_key=True, db_column='C_KEY')),
                ('c_full', models.CharField(max_length=50, null=True, db_column='C_Full', blank=True)),
                ('c_book', models.CharField(max_length=1, null=True, db_column='C_Book', blank=True)),
                ('c_main', models.CharField(max_length=1, null=True, db_column='C_Main', blank=True)),
                ('c_expires', models.CharField(max_length=1, null=True, db_column='C_Expires', blank=True)),
                ('c_interval_years', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='C_Interval_Years', blank=True)),
                ('c_interval_months', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='C_Interval_Months', blank=True)),
                ('c_time_last', models.TimeField(null=True, db_column='C_Time_Last', blank=True)),
                ('c_who_last', models.CharField(max_length=4, null=True, db_column='C_Who_Last', blank=True)),
            ],
            options={
                'db_table': 'cert',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('con_d', models.CharField(max_length=1, null=True, db_column='CON_D', blank=True)),
                ('contract', models.IntegerField(serialize=False, primary_key=True, db_column='CON_REC')),
                ('con_unique', models.CharField(max_length=10, db_column='CON_UNIQUE')),
                ('con_unique_1', models.CharField(max_length=29, db_column='CON_UNIQUE_1')),
                ('con_number', models.IntegerField(null=True, db_column='CON_Number', blank=True)),
                ('con_seq_no', models.IntegerField(null=True, db_column='CON_Seq_No', blank=True)),
                ('code', models.CharField(max_length=4, null=True, db_column='CON_B_ID', blank=True)),
                ('con_w_cs_key', models.CharField(max_length=2, null=True, db_column='CON_W_CS_KEY', blank=True)),
                ('con_t_cs_key', models.CharField(max_length=2, null=True, db_column='CON_T_CS_KEY', blank=True)),
                ('manning_agent', models.CharField(max_length=4, null=True, db_column='CON_MAN_KEY', blank=True)),
                ('principal', models.CharField(max_length=6, null=True, db_column='CON_Prin_P_KEY', blank=True)),
                ('con_master_p_key', models.CharField(max_length=6, null=True, db_column='CON_Master_P_KEY', blank=True)),
                ('wage', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Wage_W_REC', blank=True)),
                ('vessel', models.CharField(max_length=4, null=True, db_column='CON_Vsl_V_KEY', blank=True)),
                ('rank', models.CharField(max_length=4, null=True, db_column='CON_Rank_R_KEY', blank=True)),
                ('crew_category', models.CharField(max_length=1, null=True, db_column='CON_Crew_Category', blank=True)),
                ('con_m_money', models.CharField(max_length=3, null=True, db_column='CON_M_Money', blank=True)),
                ('con_length', models.IntegerField(null=True, db_column='CON_Length', blank=True)),
                ('con_pdos', models.DateField(null=True, db_column='CON_PDOS', blank=True)),
                ('con_money_beg', models.DateField(null=True, db_column='CON_Money_Beg', blank=True)),
                ('con_embark', models.DateField(null=True, db_column='CON_Embark', blank=True)),
                ('con_embark_com', models.CharField(max_length=80, null=True, db_column='CON_Embark_Com', blank=True)),
                ('con_join', models.DateField(null=True, db_column='CON_Join', blank=True)),
                ('con_join_where', models.CharField(max_length=16, null=True, db_column='CON_Join_Where', blank=True)),
                ('con_left', models.DateField(null=True, db_column='CON_Left', blank=True)),
                ('con_left_where', models.CharField(max_length=16, null=True, db_column='CON_Left_Where', blank=True)),
                ('con_disembark', models.DateField(null=True, db_column='CON_Disembark', blank=True)),
                ('con_disembark_com', models.CharField(max_length=80, null=True, db_column='CON_Disembark_Com', blank=True)),
                ('con_money_end', models.DateField(null=True, db_column='CON_Money_End', blank=True)),
                ('con_reason_signoff', models.CharField(max_length=20, null=True, db_column='CON_Reason_Signoff', blank=True)),
                ('con_date_fitness', models.DateField(null=True, db_column='CON_Date_Fitness', blank=True)),
                ('con_contract_date', models.DateField(null=True, db_column='CON_Contract_Date', blank=True)),
                ('con_poea_date', models.DateField(null=True, db_column='CON_POEA_Date', blank=True)),
                ('con_oec', models.IntegerField(null=True, db_column='CON_OEC', blank=True)),
                ('con_last_eval_rcv', models.CharField(max_length=1, null=True, db_column='CON_Last_Eval_Rcv', blank=True)),
                ('con_seniority', models.IntegerField(null=True, db_column='CON_Seniority', blank=True)),
                ('con_senior_date', models.DateField(null=True, db_column='CON_Senior_Date', blank=True)),
                ('con_mth_basic', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Mth_Basic', blank=True)),
                ('con_mth_extra1', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Mth_Extra1', blank=True)),
                ('con_mth_extra1_descr', models.CharField(max_length=32, null=True, db_column='CON_Mth_Extra1_Descr', blank=True)),
                ('con_mth_extra2', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Mth_Extra2', blank=True)),
                ('con_mth_extra2_descr', models.CharField(max_length=32, null=True, db_column='CON_Mth_Extra2_Descr', blank=True)),
                ('con_fix_mth_ot', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Fix_Mth_OT', blank=True)),
                ('con_hourly_ot_rate', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Hourly_OT_Rate', blank=True)),
                ('con_min_mth_ot_hours', models.IntegerField(null=True, db_column='CON_Min_Mth_OT_Hours', blank=True)),
                ('con_hours_week', models.IntegerField(null=True, db_column='CON_Hours_Week', blank=True)),
                ('con_comp_type_1', models.CharField(max_length=3, null=True, db_column='CON_Comp_Type_1', blank=True)),
                ('con_comp_name_1', models.CharField(max_length=16, null=True, db_column='CON_Comp_Name_1', blank=True)),
                ('con_comp_amnt_1', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Comp_Amnt_1', blank=True)),
                ('con_comp_type_2', models.CharField(max_length=3, null=True, db_column='CON_Comp_Type_2', blank=True)),
                ('con_comp_name_2', models.CharField(max_length=16, null=True, db_column='CON_Comp_Name_2', blank=True)),
                ('con_comp_amnt_2', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Comp_Amnt_2', blank=True)),
                ('con_comp_type_3', models.CharField(max_length=3, null=True, db_column='CON_Comp_Type_3', blank=True)),
                ('con_comp_name_3', models.CharField(max_length=16, null=True, db_column='CON_Comp_Name_3', blank=True)),
                ('con_comp_amnt_3', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Comp_Amnt_3', blank=True)),
                ('con_comp_type_4', models.CharField(max_length=3, null=True, db_column='CON_Comp_Type_4', blank=True)),
                ('con_comp_name_4', models.CharField(max_length=16, null=True, db_column='CON_Comp_Name_4', blank=True)),
                ('con_comp_amnt_4', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Comp_Amnt_4', blank=True)),
                ('con_comp_type_5', models.CharField(max_length=3, null=True, db_column='CON_Comp_Type_5', blank=True)),
                ('con_comp_name_5', models.CharField(max_length=16, null=True, db_column='CON_Comp_Name_5', blank=True)),
                ('con_comp_amnt_5', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Comp_Amnt_5', blank=True)),
                ('con_comp_type_6', models.CharField(max_length=3, null=True, db_column='CON_Comp_Type_6', blank=True)),
                ('con_comp_name_6', models.CharField(max_length=16, null=True, db_column='CON_Comp_Name_6', blank=True)),
                ('con_comp_amnt_6', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Comp_Amnt_6', blank=True)),
                ('con_comp_type_7', models.CharField(max_length=3, null=True, db_column='CON_Comp_Type_7', blank=True)),
                ('con_comp_name_7', models.CharField(max_length=16, null=True, db_column='CON_Comp_Name_7', blank=True)),
                ('con_comp_amnt_7', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Comp_Amnt_7', blank=True)),
                ('con_comp_type_8', models.CharField(max_length=3, null=True, db_column='CON_Comp_Type_8', blank=True)),
                ('con_comp_name_8', models.CharField(max_length=16, null=True, db_column='CON_Comp_Name_8', blank=True)),
                ('con_comp_amnt_8', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Comp_Amnt_8', blank=True)),
                ('con_comp_type_9', models.CharField(max_length=3, null=True, db_column='CON_Comp_Type_9', blank=True)),
                ('con_comp_name_9', models.CharField(max_length=16, null=True, db_column='CON_Comp_Name_9', blank=True)),
                ('con_comp_amnt_9', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Comp_Amnt_9', blank=True)),
                ('con_comp_type_10', models.CharField(max_length=3, null=True, db_column='CON_Comp_Type_10', blank=True)),
                ('con_comp_name_10', models.CharField(max_length=16, null=True, db_column='CON_Comp_Name_10', blank=True)),
                ('con_comp_amnt_10', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Comp_Amnt_10', blank=True)),
                ('con_comp_type_11', models.CharField(max_length=3, null=True, db_column='CON_Comp_Type_11', blank=True)),
                ('con_comp_name_11', models.CharField(max_length=16, null=True, db_column='CON_Comp_Name_11', blank=True)),
                ('con_comp_amnt_11', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Comp_Amnt_11', blank=True)),
                ('con_comp_type_12', models.CharField(max_length=3, null=True, db_column='CON_Comp_Type_12', blank=True)),
                ('con_comp_name_12', models.CharField(max_length=16, null=True, db_column='CON_Comp_Name_12', blank=True)),
                ('con_comp_amnt_12', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Comp_Amnt_12', blank=True)),
                ('con_comp_type_13', models.CharField(max_length=3, null=True, db_column='CON_Comp_Type_13', blank=True)),
                ('con_comp_name_13', models.CharField(max_length=16, null=True, db_column='CON_Comp_Name_13', blank=True)),
                ('con_comp_amnt_13', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Comp_Amnt_13', blank=True)),
                ('con_comp_type_14', models.CharField(max_length=3, null=True, db_column='CON_Comp_Type_14', blank=True)),
                ('con_comp_name_14', models.CharField(max_length=16, null=True, db_column='CON_Comp_Name_14', blank=True)),
                ('con_comp_amnt_14', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Comp_Amnt_14', blank=True)),
                ('con_comp_type_15', models.CharField(max_length=3, null=True, db_column='CON_Comp_Type_15', blank=True)),
                ('con_comp_name_15', models.CharField(max_length=16, null=True, db_column='CON_Comp_Name_15', blank=True)),
                ('con_comp_amnt_15', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Comp_Amnt_15', blank=True)),
                ('con_comp_type_16', models.CharField(max_length=3, null=True, db_column='CON_Comp_Type_16', blank=True)),
                ('con_comp_name_16', models.CharField(max_length=16, null=True, db_column='CON_Comp_Name_16', blank=True)),
                ('con_comp_amnt_16', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Comp_Amnt_16', blank=True)),
                ('con_comp_type_17', models.CharField(max_length=3, null=True, db_column='CON_Comp_Type_17', blank=True)),
                ('con_comp_name_17', models.CharField(max_length=16, null=True, db_column='CON_Comp_Name_17', blank=True)),
                ('con_comp_amnt_17', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Comp_Amnt_17', blank=True)),
                ('con_comp_type_18', models.CharField(max_length=3, null=True, db_column='CON_Comp_Type_18', blank=True)),
                ('con_comp_name_18', models.CharField(max_length=16, null=True, db_column='CON_Comp_Name_18', blank=True)),
                ('con_comp_amnt_18', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Comp_Amnt_18', blank=True)),
                ('con_comp_type_19', models.CharField(max_length=3, null=True, db_column='CON_Comp_Type_19', blank=True)),
                ('con_comp_name_19', models.CharField(max_length=16, null=True, db_column='CON_Comp_Name_19', blank=True)),
                ('con_comp_amnt_19', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Comp_Amnt_19', blank=True)),
                ('con_comp_type_20', models.CharField(max_length=3, null=True, db_column='CON_Comp_Type_20', blank=True)),
                ('con_comp_name_20', models.CharField(max_length=16, null=True, db_column='CON_Comp_Name_20', blank=True)),
                ('con_comp_amnt_20', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Comp_Amnt_20', blank=True)),
                ('con_comp_type_21', models.CharField(max_length=3, null=True, db_column='CON_Comp_Type_21', blank=True)),
                ('con_comp_name_21', models.CharField(max_length=16, null=True, db_column='CON_Comp_Name_21', blank=True)),
                ('con_comp_amnt_21', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Comp_Amnt_21', blank=True)),
                ('con_comp_type_22', models.CharField(max_length=3, null=True, db_column='CON_Comp_Type_22', blank=True)),
                ('con_comp_name_22', models.CharField(max_length=16, null=True, db_column='CON_Comp_Name_22', blank=True)),
                ('con_comp_amnt_22', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Comp_Amnt_22', blank=True)),
                ('con_comp_type_23', models.CharField(max_length=3, null=True, db_column='CON_Comp_Type_23', blank=True)),
                ('con_comp_name_23', models.CharField(max_length=16, null=True, db_column='CON_Comp_Name_23', blank=True)),
                ('con_comp_amnt_23', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Comp_Amnt_23', blank=True)),
                ('con_comp_type_24', models.CharField(max_length=3, null=True, db_column='CON_Comp_Type_24', blank=True)),
                ('con_comp_name_24', models.CharField(max_length=16, null=True, db_column='CON_Comp_Name_24', blank=True)),
                ('con_comp_amnt_24', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Comp_Amnt_24', blank=True)),
                ('con_pays_nat', models.CharField(max_length=1, null=True, db_column='CON_Pays_NAT', blank=True)),
                ('con_pays_seaman_home', models.CharField(max_length=1, null=True, db_column='CON_Pays_Seaman_Home', blank=True)),
                ('con_pays_fmy', models.CharField(max_length=1, null=True, db_column='CON_Pays_FMY', blank=True)),
                ('con_pays_tax', models.CharField(max_length=1, null=True, db_column='CON_Pays_TAX', blank=True)),
                ('con_pays_pno', models.CharField(max_length=1, null=True, db_column='CON_Pays_PNO', blank=True)),
                ('con_leave_onsignoff', models.CharField(max_length=1, null=True, db_column='CON_Leave_OnSignoff', blank=True)),
                ('con_seniority_rank', models.IntegerField(null=True, db_column='CON_Seniority_Rank', blank=True)),
                ('con_senior_rank_date', models.DateField(null=True, db_column='CON_Senior_Rank_Date', blank=True)),
                ('con_ereceipt', models.IntegerField(null=True, db_column='CON_EReceipt', blank=True)),
                ('con_cba', models.CharField(max_length=12, null=True, db_column='CON_CBA', blank=True)),
                ('con_bmi', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_BMI', blank=True)),
                ('con_cash_advance', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Cash_Advance', blank=True)),
                ('con_tax_anal', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Tax_Anal', blank=True)),
                ('con_p_alo', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_P_ALO', blank=True)),
                ('con_balance_total', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Balance_Total', blank=True)),
                ('con_balance_amt_cur1', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Balance_Amt_Cur1', blank=True)),
                ('con_balance_cur1', models.CharField(max_length=3, null=True, db_column='CON_Balance_Cur1', blank=True)),
                ('con_balance_amt_cur2', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Balance_Amt_Cur2', blank=True)),
                ('con_balance_cur2', models.CharField(max_length=3, null=True, db_column='CON_Balance_Cur2', blank=True)),
                ('con_balance_amt_cur3', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Balance_Amt_Cur3', blank=True)),
                ('con_balance_cur3', models.CharField(max_length=3, null=True, db_column='CON_Balance_Cur3', blank=True)),
                ('con_balance_comment', models.CharField(max_length=32, null=True, db_column='CON_Balance_Comment', blank=True)),
                ('con_balance_status', models.CharField(max_length=1, null=True, db_column='CON_Balance_Status', blank=True)),
                ('con_balance_payday', models.DateField(null=True, db_column='CON_Balance_Payday', blank=True)),
                ('con_retro1_from', models.DateField(null=True, db_column='CON_Retro1_From', blank=True)),
                ('con_retro1_to', models.DateField(null=True, db_column='CON_Retro1_To', blank=True)),
                ('con_retro1_total', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Retro1_Total', blank=True)),
                ('con_retro1_amt_cur1', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Retro1_Amt_Cur1', blank=True)),
                ('con_retro1_cur1', models.CharField(max_length=3, null=True, db_column='CON_Retro1_Cur1', blank=True)),
                ('con_retro1_amt_cur2', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Retro1_Amt_Cur2', blank=True)),
                ('con_retro1_cur2', models.CharField(max_length=3, null=True, db_column='CON_Retro1_Cur2', blank=True)),
                ('con_retro1_amt_cur3', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Retro1_Amt_Cur3', blank=True)),
                ('con_retro1_cur3', models.CharField(max_length=3, null=True, db_column='CON_Retro1_Cur3', blank=True)),
                ('con_retro1_status', models.CharField(max_length=1, null=True, db_column='CON_Retro1_Status', blank=True)),
                ('con_retro1_payday', models.DateField(null=True, db_column='CON_Retro1_Payday', blank=True)),
                ('con_retro1_comment', models.CharField(max_length=32, null=True, db_column='CON_Retro1_Comment', blank=True)),
                ('con_retro2_from', models.DateField(null=True, db_column='CON_Retro2_From', blank=True)),
                ('con_retro2_to', models.DateField(null=True, db_column='CON_Retro2_To', blank=True)),
                ('con_retro2_total', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Retro2_Total', blank=True)),
                ('con_retro2_amt_cur1', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Retro2_Amt_Cur1', blank=True)),
                ('con_retro2_cur1', models.CharField(max_length=3, null=True, db_column='CON_Retro2_Cur1', blank=True)),
                ('con_retro2_amt_cur2', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Retro2_Amt_Cur2', blank=True)),
                ('con_retro2_cur2', models.CharField(max_length=3, null=True, db_column='CON_Retro2_Cur2', blank=True)),
                ('con_retro2_amt_cur3', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Retro2_Amt_Cur3', blank=True)),
                ('con_retro2_cur3', models.CharField(max_length=3, null=True, db_column='CON_Retro2_Cur3', blank=True)),
                ('con_retro2_status', models.CharField(max_length=1, null=True, db_column='CON_Retro2_Status', blank=True)),
                ('con_retro2_payday', models.DateField(null=True, db_column='CON_Retro2_Payday', blank=True)),
                ('con_retro2_comment', models.CharField(max_length=32, null=True, db_column='CON_Retro2_Comment', blank=True)),
                ('con_retro3_from', models.DateField(null=True, db_column='CON_Retro3_From', blank=True)),
                ('con_retro3_to', models.DateField(null=True, db_column='CON_Retro3_To', blank=True)),
                ('con_retro3_total', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Retro3_Total', blank=True)),
                ('con_retro3_amt_cur1', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Retro3_Amt_Cur1', blank=True)),
                ('con_retro3_cur1', models.CharField(max_length=3, null=True, db_column='CON_Retro3_Cur1', blank=True)),
                ('con_retro3_amt_cur2', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Retro3_Amt_Cur2', blank=True)),
                ('con_retro3_cur2', models.CharField(max_length=3, null=True, db_column='CON_Retro3_Cur2', blank=True)),
                ('con_retro3_amt_cur3', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='CON_Retro3_Amt_Cur3', blank=True)),
                ('con_retro3_cur3', models.CharField(max_length=3, null=True, db_column='CON_Retro3_Cur3', blank=True)),
                ('con_retro3_status', models.CharField(max_length=1, null=True, db_column='CON_Retro3_Status', blank=True)),
                ('con_retro3_payday', models.DateField(null=True, db_column='CON_Retro3_Payday', blank=True)),
                ('con_retro3_comment', models.CharField(max_length=32, null=True, db_column='CON_Retro3_Comment', blank=True)),
                ('con_time_last', models.TimeField(null=True, db_column='CON_Time_Last', blank=True)),
                ('con_who_last', models.CharField(max_length=4, null=True, db_column='CON_Who_Last', blank=True)),
            ],
            options={
                'db_table': 'contract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('cn_d', models.CharField(max_length=1, null=True, db_column='CN_D', blank=True)),
                ('country', models.CharField(max_length=2, serialize=False, primary_key=True, db_column='CN_KEY')),
                ('cn_full', models.CharField(max_length=45, null=True, db_column='CN_Full', blank=True)),
                ('cn_nationality', models.CharField(max_length=20, null=True, db_column='CN_Nationality', blank=True)),
                ('cn_time_last', models.TimeField(null=True, db_column='CN_Time_Last', blank=True)),
                ('cn_who_last', models.CharField(max_length=4, null=True, db_column='CN_Who_Last', blank=True)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('d_d', models.CharField(max_length=1, null=True, db_column='D_D', blank=True)),
                ('doc', models.IntegerField(serialize=False, primary_key=True, db_column='D_REC')),
                ('d_unique', models.CharField(max_length=9, null=True, db_column='D_UNIQUE', blank=True)),
                ('code', models.CharField(max_length=4, null=True, db_column='D_ID_B_ID', blank=True)),
                ('d_number', models.CharField(max_length=32, null=True, db_column='D_Number', blank=True)),
                ('d_rank_r_key', models.CharField(max_length=4, null=True, db_column='D_Rank_R_KEY', blank=True)),
                ('d_issue', models.DateField(null=True, db_column='D_Issue', blank=True)),
                ('d_expire', models.DateField(null=True, db_column='D_Expire', blank=True)),
                ('d_othercountry', models.CharField(max_length=2, null=True, db_column='D_OtherCountry', blank=True)),
                ('d_time_last', models.TimeField(null=True, db_column='D_Time_Last', blank=True)),
                ('d_who_last', models.CharField(max_length=4, null=True, db_column='D_Who_Last', blank=True)),
            ],
            options={
                'db_table': 'doc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('p_d', models.CharField(max_length=1, null=True, db_column='P_D', blank=True)),
                ('principal', models.CharField(max_length=6, serialize=False, primary_key=True, db_column='P_KEY')),
                ('p_master_p_key', models.CharField(max_length=6, null=True, db_column='P_Master_P_KEY', blank=True)),
                ('p_full', models.CharField(max_length=40, null=True, db_column='P_Full', blank=True)),
                ('p_sss', models.CharField(max_length=12, null=True, db_column='P_SSS', blank=True)),
                ('p_accredno', models.CharField(max_length=12, null=True, db_column='P_AccredNo', blank=True)),
                ('p_addr1', models.CharField(max_length=32, null=True, db_column='P_Addr1', blank=True)),
                ('p_addr2', models.CharField(max_length=32, null=True, db_column='P_Addr2', blank=True)),
                ('p_addr3', models.CharField(max_length=32, null=True, db_column='P_Addr3', blank=True)),
                ('p_lawcountry', models.CharField(max_length=24, null=True, db_column='P_LawCountry', blank=True)),
                ('p_telephone', models.CharField(max_length=32, null=True, db_column='P_Telephone', blank=True)),
                ('p_email_address', models.CharField(max_length=36, null=True, db_column='P_Email_Address', blank=True)),
                ('p_acct_category_a', models.CharField(max_length=16, null=True, db_column='P_Acct_Category_A', blank=True)),
                ('p_acct_category_b', models.CharField(max_length=16, null=True, db_column='P_Acct_Category_B', blank=True)),
                ('p_acct_category_c', models.CharField(max_length=16, null=True, db_column='P_Acct_Category_C', blank=True)),
                ('p_acct_category_d', models.CharField(max_length=16, null=True, db_column='P_Acct_Category_D', blank=True)),
                ('p_acct_category_e', models.CharField(max_length=16, null=True, db_column='P_Acct_Category_E', blank=True)),
                ('p_acct_category_f', models.CharField(max_length=16, null=True, db_column='P_Acct_Category_F', blank=True)),
                ('p_acct_category_g', models.CharField(max_length=16, null=True, db_column='P_Acct_Category_G', blank=True)),
                ('p_acct_expenses', models.CharField(max_length=16, null=True, db_column='P_Acct_Expenses', blank=True)),
                ('p_time_last', models.TimeField(null=True, db_column='P_Time_Last', blank=True)),
                ('p_who_last', models.CharField(max_length=4, null=True, db_column='P_Who_Last', blank=True)),
            ],
            options={
                'db_table': 'principal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('r_d', models.CharField(max_length=1, null=True, db_column='R_D', blank=True)),
                ('rank', models.CharField(max_length=4, serialize=False, primary_key=True, db_column='R_KEY')),
                ('r_full', models.CharField(max_length=16, null=True, db_column='R_Full', blank=True)),
                ('r_grk_desc', models.CharField(max_length=20, null=True, db_column='R_Grk_Desc', blank=True)),
                ('r_sort', models.CharField(max_length=2, null=True, db_column='R_Sort', blank=True)),
                ('r_tc_key', models.CharField(max_length=1, null=True, db_column='R_TC_KEY', blank=True)),
                ('r_officer', models.CharField(max_length=1, null=True, db_column='R_Officer', blank=True)),
                ('r_time_last', models.TimeField(null=True, db_column='R_Time_Last', blank=True)),
                ('r_who_last', models.CharField(max_length=4, null=True, db_column='R_Who_Last', blank=True)),
            ],
            options={
                'db_table': 'rank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('v_d', models.CharField(max_length=1, null=True, db_column='V_D', blank=True)),
                ('vessel', models.CharField(max_length=4, serialize=False, primary_key=True, db_column='V_KEY')),
                ('v_full', models.CharField(max_length=32, null=True, db_column='V_Full', blank=True)),
                ('principal', models.CharField(max_length=6, null=True, verbose_name='Principal', db_column='V_P_KEY', blank=True)),
                ('v_registry', models.CharField(max_length=12, null=True, db_column='V_Registry', blank=True)),
                ('v_cn_key', models.CharField(max_length=2, null=True, db_column='V_CN_KEY', blank=True)),
                ('v_regnumber', models.CharField(max_length=16, null=True, db_column='V_RegNumber', blank=True)),
                ('v_grt', models.IntegerField(null=True, db_column='V_GRT', blank=True)),
                ('v_nrt', models.IntegerField(null=True, db_column='V_NRT', blank=True)),
                ('v_dwt', models.CharField(max_length=8, null=True, db_column='V_DWT', blank=True)),
                ('v_engine', models.CharField(max_length=6, null=True, db_column='V_Engine', blank=True)),
                ('v_horsepower', models.CharField(max_length=8, null=True, db_column='V_HorsePower', blank=True)),
                ('v_class', models.CharField(max_length=4, null=True, db_column='V_Class', blank=True)),
                ('v_yard', models.CharField(max_length=12, null=True, db_column='V_Yard', blank=True)),
                ('v_yearbuilt', models.IntegerField(null=True, db_column='V_YearBuilt', blank=True)),
                ('v_trades', models.CharField(max_length=16, null=True, db_column='V_Trades', blank=True)),
                ('v_ums', models.CharField(max_length=1, null=True, db_column='V_UMS', blank=True)),
                ('v_callsign', models.CharField(max_length=6, null=True, db_column='V_CallSign', blank=True)),
                ('v_owner_ship', models.CharField(max_length=45, null=True, db_column='V_Owner_Ship', blank=True)),
                ('v_imo', models.CharField(max_length=12, null=True, db_column='V_IMO', blank=True)),
                ('v_status', models.CharField(max_length=1, null=True, db_column='V_Status', blank=True)),
                ('v_end', models.DateField(null=True, db_column='V_End', blank=True)),
                ('v_reason', models.CharField(max_length=18, null=True, db_column='V_Reason', blank=True)),
                ('v_main_cat', models.CharField(max_length=1, null=True, db_column='V_Main_Cat', blank=True)),
                ('v_equip_1', models.CharField(max_length=4, null=True, db_column='V_Equip_1', blank=True)),
                ('v_equip_2', models.CharField(max_length=4, null=True, db_column='V_Equip_2', blank=True)),
                ('v_equip_3', models.CharField(max_length=4, null=True, db_column='V_Equip_3', blank=True)),
                ('v_equip_4', models.CharField(max_length=4, null=True, db_column='V_Equip_4', blank=True)),
                ('v_pays_nat', models.CharField(max_length=1, null=True, db_column='V_Pays_NAT', blank=True)),
                ('v_pays_fmy', models.CharField(max_length=1, null=True, db_column='V_Pays_FMY', blank=True)),
                ('v_pays_pno', models.CharField(max_length=1, null=True, db_column='V_Pays_PNO', blank=True)),
                ('v_pays_tax', models.CharField(max_length=1, null=True, db_column='V_Pays_TAX', blank=True)),
                ('v_p_post_date', models.DateField(null=True, db_column='V_P_Post_Date', blank=True)),
                ('v_r_post_date', models.DateField(null=True, db_column='V_R_Post_Date', blank=True)),
                ('v_e_post_date', models.DateField(null=True, db_column='V_E_Post_Date', blank=True)),
                ('v_tfs_fleet', models.CharField(max_length=1, null=True, db_column='V_TFS_Fleet', blank=True)),
                ('v_tfs_ship', models.CharField(max_length=4, null=True, db_column='V_TFS_Ship', blank=True)),
                ('v_email_1', models.CharField(max_length=28, null=True, db_column='V_Email_1', blank=True)),
                ('v_email_2', models.CharField(max_length=28, null=True, db_column='V_Email_2', blank=True)),
                ('v_time_last', models.TimeField(null=True, db_column='V_Time_Last', blank=True)),
                ('v_who_last', models.CharField(max_length=4, null=True, db_column='V_Who_Last', blank=True)),
            ],
            options={
                'db_table': 'vessel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vtype',
            fields=[
                ('vt_d', models.CharField(max_length=1, null=True, db_column='VT_D', blank=True)),
                ('vessel_type', models.CharField(max_length=4, serialize=False, primary_key=True, db_column='VT_KEY')),
                ('vt_full', models.CharField(max_length=16, null=True, db_column='VT_Full', blank=True)),
                ('vt_time_last', models.TimeField(null=True, db_column='VT_Time_Last', blank=True)),
                ('vt_who_last', models.CharField(max_length=4, null=True, db_column='VT_Who_Last', blank=True)),
            ],
            options={
                'db_table': 'vtype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('w_d', models.CharField(max_length=1, null=True, db_column='W_D', blank=True)),
                ('w_rec', models.IntegerField(db_column='W_REC')),
                ('w_unique', models.CharField(max_length=23, db_column='W_UNIQUE')),
                ('w_unique_1', models.CharField(max_length=23, db_column='W_UNIQUE_1')),
                ('w_p_key', models.CharField(max_length=6, null=True, db_column='W_P_KEY', blank=True)),
                ('w_date', models.DateField(null=True, db_column='W_Date', blank=True)),
                ('w_rank_r_key', models.CharField(max_length=4, null=True, db_column='W_Rank_R_KEY', blank=True)),
                ('w_cs_key', models.CharField(max_length=2, null=True, db_column='W_CS_KEY', blank=True)),
                ('w_m_money', models.CharField(max_length=3, null=True, db_column='W_M_Money', blank=True)),
                ('w_mth_basic', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Mth_Basic', blank=True)),
                ('w_fix_mth_ot', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Fix_Mth_OT', blank=True)),
                ('w_hourly_ot_rate', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Hourly_OT_Rate', blank=True)),
                ('w_min_mth_ot_hours', models.IntegerField(null=True, db_column='W_Min_Mth_OT_Hours', blank=True)),
                ('w_hours_week', models.IntegerField(null=True, db_column='W_Hours_Week', blank=True)),
                ('w_comp_type_1', models.CharField(max_length=3, null=True, db_column='W_Comp_Type_1', blank=True)),
                ('w_comp_name_1', models.CharField(max_length=16, null=True, db_column='W_Comp_Name_1', blank=True)),
                ('w_comp_amnt_1', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Comp_Amnt_1', blank=True)),
                ('w_comp_type_2', models.CharField(max_length=3, null=True, db_column='W_Comp_Type_2', blank=True)),
                ('w_comp_name_2', models.CharField(max_length=16, null=True, db_column='W_Comp_Name_2', blank=True)),
                ('w_comp_amnt_2', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Comp_Amnt_2', blank=True)),
                ('w_comp_type_3', models.CharField(max_length=3, null=True, db_column='W_Comp_Type_3', blank=True)),
                ('w_comp_name_3', models.CharField(max_length=16, null=True, db_column='W_Comp_Name_3', blank=True)),
                ('w_comp_amnt_3', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Comp_Amnt_3', blank=True)),
                ('w_comp_type_4', models.CharField(max_length=3, null=True, db_column='W_Comp_Type_4', blank=True)),
                ('w_comp_name_4', models.CharField(max_length=16, null=True, db_column='W_Comp_Name_4', blank=True)),
                ('w_comp_amnt_4', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Comp_Amnt_4', blank=True)),
                ('w_comp_type_5', models.CharField(max_length=3, null=True, db_column='W_Comp_Type_5', blank=True)),
                ('w_comp_name_5', models.CharField(max_length=16, null=True, db_column='W_Comp_Name_5', blank=True)),
                ('w_comp_amnt_5', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Comp_Amnt_5', blank=True)),
                ('w_comp_type_6', models.CharField(max_length=3, null=True, db_column='W_Comp_Type_6', blank=True)),
                ('w_comp_name_6', models.CharField(max_length=16, null=True, db_column='W_Comp_Name_6', blank=True)),
                ('w_comp_amnt_6', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Comp_Amnt_6', blank=True)),
                ('w_comp_type_7', models.CharField(max_length=3, null=True, db_column='W_Comp_Type_7', blank=True)),
                ('w_comp_name_7', models.CharField(max_length=16, null=True, db_column='W_Comp_Name_7', blank=True)),
                ('w_comp_amnt_7', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Comp_Amnt_7', blank=True)),
                ('w_comp_type_8', models.CharField(max_length=3, null=True, db_column='W_Comp_Type_8', blank=True)),
                ('w_comp_name_8', models.CharField(max_length=16, null=True, db_column='W_Comp_Name_8', blank=True)),
                ('w_comp_amnt_8', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Comp_Amnt_8', blank=True)),
                ('w_comp_type_9', models.CharField(max_length=3, null=True, db_column='W_Comp_Type_9', blank=True)),
                ('w_comp_name_9', models.CharField(max_length=16, null=True, db_column='W_Comp_Name_9', blank=True)),
                ('w_comp_amnt_9', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Comp_Amnt_9', blank=True)),
                ('w_comp_type_10', models.CharField(max_length=3, null=True, db_column='W_Comp_Type_10', blank=True)),
                ('w_comp_name_10', models.CharField(max_length=16, null=True, db_column='W_Comp_Name_10', blank=True)),
                ('w_comp_amnt_10', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Comp_Amnt_10', blank=True)),
                ('w_comp_type_11', models.CharField(max_length=3, null=True, db_column='W_Comp_Type_11', blank=True)),
                ('w_comp_name_11', models.CharField(max_length=16, null=True, db_column='W_Comp_Name_11', blank=True)),
                ('w_comp_amnt_11', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Comp_Amnt_11', blank=True)),
                ('w_comp_type_12', models.CharField(max_length=3, null=True, db_column='W_Comp_Type_12', blank=True)),
                ('w_comp_name_12', models.CharField(max_length=16, null=True, db_column='W_Comp_Name_12', blank=True)),
                ('w_comp_amnt_12', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Comp_Amnt_12', blank=True)),
                ('w_comp_type_13', models.CharField(max_length=3, null=True, db_column='W_Comp_Type_13', blank=True)),
                ('w_comp_name_13', models.CharField(max_length=16, null=True, db_column='W_Comp_Name_13', blank=True)),
                ('w_comp_amnt_13', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Comp_Amnt_13', blank=True)),
                ('w_comp_type_14', models.CharField(max_length=3, null=True, db_column='W_Comp_Type_14', blank=True)),
                ('w_comp_name_14', models.CharField(max_length=16, null=True, db_column='W_Comp_Name_14', blank=True)),
                ('w_comp_amnt_14', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Comp_Amnt_14', blank=True)),
                ('w_comp_type_15', models.CharField(max_length=3, null=True, db_column='W_Comp_Type_15', blank=True)),
                ('w_comp_name_15', models.CharField(max_length=16, null=True, db_column='W_Comp_Name_15', blank=True)),
                ('w_comp_amnt_15', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Comp_Amnt_15', blank=True)),
                ('w_comp_type_16', models.CharField(max_length=3, null=True, db_column='W_Comp_Type_16', blank=True)),
                ('w_comp_name_16', models.CharField(max_length=16, null=True, db_column='W_Comp_Name_16', blank=True)),
                ('w_comp_amnt_16', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Comp_Amnt_16', blank=True)),
                ('w_comp_type_17', models.CharField(max_length=3, null=True, db_column='W_Comp_Type_17', blank=True)),
                ('w_comp_name_17', models.CharField(max_length=16, null=True, db_column='W_Comp_Name_17', blank=True)),
                ('w_comp_amnt_17', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Comp_Amnt_17', blank=True)),
                ('w_comp_type_18', models.CharField(max_length=3, null=True, db_column='W_Comp_Type_18', blank=True)),
                ('w_comp_name_18', models.CharField(max_length=16, null=True, db_column='W_Comp_Name_18', blank=True)),
                ('w_comp_amnt_18', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Comp_Amnt_18', blank=True)),
                ('w_comp_type_19', models.CharField(max_length=3, null=True, db_column='W_Comp_Type_19', blank=True)),
                ('w_comp_name_19', models.CharField(max_length=16, null=True, db_column='W_Comp_Name_19', blank=True)),
                ('w_comp_amnt_19', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Comp_Amnt_19', blank=True)),
                ('w_comp_type_20', models.CharField(max_length=3, null=True, db_column='W_Comp_Type_20', blank=True)),
                ('w_comp_name_20', models.CharField(max_length=16, null=True, db_column='W_Comp_Name_20', blank=True)),
                ('w_comp_amnt_20', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Comp_Amnt_20', blank=True)),
                ('w_comp_type_21', models.CharField(max_length=3, null=True, db_column='W_Comp_Type_21', blank=True)),
                ('w_comp_name_21', models.CharField(max_length=16, null=True, db_column='W_Comp_Name_21', blank=True)),
                ('w_comp_amnt_21', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Comp_Amnt_21', blank=True)),
                ('w_comp_type_22', models.CharField(max_length=3, null=True, db_column='W_Comp_Type_22', blank=True)),
                ('w_comp_name_22', models.CharField(max_length=16, null=True, db_column='W_Comp_Name_22', blank=True)),
                ('w_comp_amnt_22', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Comp_Amnt_22', blank=True)),
                ('w_comp_type_23', models.CharField(max_length=3, null=True, db_column='W_Comp_Type_23', blank=True)),
                ('w_comp_name_23', models.CharField(max_length=16, null=True, db_column='W_Comp_Name_23', blank=True)),
                ('w_comp_amnt_23', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Comp_Amnt_23', blank=True)),
                ('w_comp_type_24', models.CharField(max_length=3, null=True, db_column='W_Comp_Type_24', blank=True)),
                ('w_comp_name_24', models.CharField(max_length=16, null=True, db_column='W_Comp_Name_24', blank=True)),
                ('w_comp_amnt_24', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Comp_Amnt_24', blank=True)),
                ('w_sen_1', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Sen_1', blank=True)),
                ('w_sen_2', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Sen_2', blank=True)),
                ('w_sen_3', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Sen_3', blank=True)),
                ('w_sen_4', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Sen_4', blank=True)),
                ('w_sen_5', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Sen_5', blank=True)),
                ('w_sen_6', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Sen_6', blank=True)),
                ('w_sen_7', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Sen_7', blank=True)),
                ('w_sen_8', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Sen_8', blank=True)),
                ('w_sen_9', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Sen_9', blank=True)),
                ('w_sen_10', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Sen_10', blank=True)),
                ('w_sen_11', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Sen_11', blank=True)),
                ('w_sen_rank_1', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Sen_Rank_1', blank=True)),
                ('w_sen_rank_2', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Sen_Rank_2', blank=True)),
                ('w_sen_rank_3', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Sen_Rank_3', blank=True)),
                ('w_sen_rank_4', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Sen_Rank_4', blank=True)),
                ('w_sen_rank_5', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Sen_Rank_5', blank=True)),
                ('w_sen_rank_6', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Sen_Rank_6', blank=True)),
                ('w_sen_rank_7', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Sen_Rank_7', blank=True)),
                ('w_sen_rank_8', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Sen_Rank_8', blank=True)),
                ('w_sen_rank_9', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Sen_Rank_9', blank=True)),
                ('w_sen_rank_10', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Sen_Rank_10', blank=True)),
                ('w_sen_rank_11', models.DecimalField(null=True, decimal_places=0, max_digits=10, db_column='W_Sen_Rank_11', blank=True)),
                ('w_time_last', models.TimeField(null=True, db_column='W_Time_Last', blank=True)),
                ('w_who_last', models.CharField(max_length=4, null=True, db_column='W_Who_Last', blank=True)),
            ],
            options={
                'db_table': 'wage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('s_d', models.CharField(max_length=1, null=True, db_column='S_D', blank=True)),
                ('s_rec', models.IntegerField(serialize=False, primary_key=True, db_column='S_REC')),
                ('s_unique', models.CharField(max_length=13, db_column='S_UNIQUE')),
                ('contract', models.CharField(max_length=20, null=True, db_column='S_CON_UNIQUE')),
                ('code', models.CharField(max_length=4, null=True, db_column='S_ID_B_ID')),
                ('s_start', models.DateField(null=True, db_column='S_Start', blank=True)),
                ('s_end', models.DateField(null=True, db_column='S_End', blank=True)),
                ('s_why', models.CharField(max_length=1, null=True, db_column='S_Why', blank=True)),
                ('s_rank_r_key', models.CharField(max_length=4, null=True, db_column='S_Rank_R_KEY', blank=True)),
                ('s_vsl_v_key', models.CharField(max_length=4, null=True, db_column='S_Vsl_V_KEY', blank=True)),
                ('s_vsl_name', models.CharField(max_length=20, null=True, db_column='S_Vsl_Name', blank=True)),
                ('s_principal', models.CharField(max_length=20, null=True, db_column='S_Principal', blank=True)),
                ('s_cn_key', models.CharField(max_length=2, null=True, db_column='S_CN_KEY', blank=True)),
                ('s_grt', models.CharField(max_length=6, null=True, db_column='S_GRT', blank=True)),
                ('s_type_vt_key', models.CharField(max_length=4, null=True, db_column='S_Type_VT_KEY', blank=True)),
                ('s_engine', models.CharField(max_length=6, null=True, db_column='S_Engine', blank=True)),
                ('s_horsepower', models.CharField(max_length=8, null=True, db_column='S_HorsePower', blank=True)),
                ('s_time_last', models.TimeField(null=True, db_column='S_Time_Last', blank=True)),
                ('s_who_last', models.CharField(max_length=4, null=True, db_column='S_Who_Last', blank=True)),
            ],
            options={
                'db_table': 'service',
                'managed': True,
            },
        ),
    ]
