# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BIO_DATA',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('B_D', models.CharField(max_length=1, null=True)),
                ('B_ID', models.CharField(unique=True, max_length=4)),
                ('B_UID', models.IntegerField()),
                ('B_Last_Name', models.CharField(max_length=18)),
                ('B_First_Name', models.CharField(max_length=28)),
                ('B_Middle_Name', models.CharField(max_length=18)),
                ('B_Suffix_Name', models.CharField(max_length=5)),
                ('B_Father_Name', models.CharField(max_length=18)),
                ('B_Mother_Name', models.CharField(max_length=18)),
                ('B_CN_KEY', models.CharField(max_length=2)),
                ('B_Bio_Status', models.CharField(max_length=1)),
                ('B_Available', models.CharField(max_length=8)),
                ('B_Position_1st', models.CharField(max_length=4)),
                ('B_Ex_Crew', models.CharField(max_length=1)),
                ('B_Last_V_KEY', models.CharField(max_length=4)),
                ('B_Birth_Date', models.DateTimeField()),
                ('B_Birth_Place', models.CharField(max_length=32)),
                ('B_Height', models.CharField(max_length=5)),
                ('B_Weight', models.CharField(max_length=5)),
                ('B_BMI', models.CharField(max_length=5)),
                ('B_Phone_1', models.CharField(max_length=16)),
                ('B_Phone_2', models.CharField(max_length=16)),
                ('B_Metro_Addr_1', models.CharField(max_length=32)),
                ('B_Metro_Addr_2', models.CharField(max_length=32)),
                ('B_Metro_Addr_3', models.CharField(max_length=32)),
                ('B_Metro_Addr_4', models.CharField(max_length=32)),
                ('B_Prov_Addr_1', models.CharField(max_length=16)),
                ('B_Prov_Addr_2', models.CharField(max_length=16)),
                ('B_Prov_Addr_3', models.CharField(max_length=16)),
                ('B_Marital_Status', models.CharField(max_length=1)),
                ('B_Number_Dependents', models.IntegerField()),
                ('B_Emergency_Name', models.CharField(max_length=24)),
                ('B_Emergency_Relation', models.CharField(max_length=4)),
                ('B_Emergency_Phone', models.CharField(max_length=16)),
                ('B_Emergency_Addr_1', models.CharField(max_length=32)),
                ('B_Emergency_Addr_2', models.CharField(max_length=32)),
                ('B_Emergency_Addr_3', models.CharField(max_length=32)),
                ('B_Emergency_Addr_4', models.CharField(max_length=32)),
                ('B_Educ_Note_1', models.CharField(max_length=34)),
                ('B_Educ_Note_2', models.CharField(max_length=34)),
                ('B_Mother_Language', models.CharField(max_length=8)),
                ('B_English', models.CharField(max_length=1)),
                ('B_Comments', models.CharField(max_length=60)),
                ('B_Wife_Name', models.CharField(max_length=34)),
                ('B_Wife_BirthDate', models.IntegerField()),
                ('B_Wife_Job', models.CharField(max_length=1)),
                ('B_Tax_Status', models.CharField(max_length=1)),
                ('B_Tax_Acct', models.CharField(max_length=20)),
                ('B_Tax_Office', models.CharField(max_length=30)),
                ('B_SSS', models.CharField(max_length=16)),
                ('B_PHealth', models.CharField(max_length=16)),
                ('B_Vocational', models.CharField(max_length=16)),
                ('B_HS_Grad', models.CharField(max_length=1)),
                ('B_HS_Date', models.DateTimeField()),
                ('B_Nautical_School', models.CharField(max_length=16)),
                ('B_Nautical_Degree', models.CharField(max_length=4)),
                ('B_Nautical_Date', models.DateTimeField()),
                ('B_Other_School', models.CharField(max_length=8)),
                ('B_Other_Degree', models.CharField(max_length=8)),
                ('B_Other_Date', models.DateTimeField()),
                ('B_Union', models.CharField(max_length=1)),
                ('B_Separation_Type', models.CharField(max_length=1)),
                ('B_Sea_Months', models.IntegerField(verbose_name=3)),
                ('B_Nick_Name', models.CharField(max_length=12)),
                ('B_Email_Address', models.CharField(max_length=45)),
                ('B_OFW_ID', models.CharField(max_length=32)),
                ('B_Pagibig', models.CharField(max_length=16)),
                ('B_Time_Last', models.DateTimeField()),
                ('B_Who_Last', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('C_D', models.CharField(max_length=1, null=True)),
                ('C_KEY', models.CharField(max_length=5)),
                ('C_Full', models.CharField(max_length=50)),
                ('C_Book', models.CharField(max_length=1)),
                ('C_Main', models.CharField(max_length=1)),
                ('C_Expires', models.CharField(max_length=1)),
                ('C_Interval_Years', models.IntegerField()),
                ('C_Interval_Months', models.IntegerField()),
                ('C_Time_Last', models.DateTimeField()),
                ('C_Who_Last', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DOCUMENTS',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('D_D', models.CharField(max_length=1, null=True)),
                ('D_REC', models.IntegerField()),
                ('D_UNIQUE', models.CharField(max_length=9)),
                ('D_ID_B_ID', models.CharField(max_length=4)),
                ('D_Cert_C_KEY', models.CharField(max_length=4)),
                ('D_Number', models.CharField(max_length=32)),
                ('D_Rank_R_KEY', models.CharField(max_length=4)),
                ('D_Issue', models.DateTimeField()),
                ('D_Expire', models.DateTimeField()),
                ('D_OtherCountry', models.CharField(max_length=2)),
                ('D_Time_Last', models.DateTimeField()),
                ('D_Who_Last', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='PRINCIPALS',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('P_D', models.CharField(max_length=1, null=True)),
                ('P_KEY', models.CharField(max_length=6)),
                ('P_Master_P_KEY', models.CharField(max_length=6)),
                ('P_Full', models.CharField(max_length=40)),
                ('P_SSS', models.CharField(max_length=12)),
                ('P_AccredNo', models.CharField(max_length=12)),
                ('P_Addr1', models.CharField(max_length=32)),
                ('P_Addr2', models.CharField(max_length=32)),
                ('P_Addr3', models.CharField(max_length=32)),
                ('P_LawCountry', models.CharField(max_length=24)),
                ('P_Telephone', models.CharField(max_length=32)),
                ('P_Email_Address', models.CharField(max_length=36)),
                ('P_Acct_Category_A', models.CharField(max_length=16)),
                ('P_Acct_Category_B', models.CharField(max_length=16)),
                ('P_Acct_Category_C', models.CharField(max_length=16)),
                ('P_Acct_Category_D', models.CharField(max_length=16)),
                ('P_Acct_Category_E', models.CharField(max_length=16)),
                ('P_Acct_Category_F', models.CharField(max_length=16)),
                ('P_Acct_Category_G', models.CharField(max_length=16)),
                ('P_Acct_Expenses', models.CharField(max_length=16)),
                ('P_Time_Last', models.DateTimeField()),
                ('P_Who_Last', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RANKS',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('R_D', models.CharField(max_length=1, null=True)),
                ('R_KEY', models.CharField(max_length=4)),
                ('R_Full', models.CharField(max_length=16)),
                ('R_Sort', models.CharField(max_length=2)),
                ('R_TC_KEY', models.CharField(max_length=1)),
                ('R_Officer', models.CharField(max_length=1)),
                ('R_Time_Last', models.DateTimeField()),
                ('R_Who_Last', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='RequiredCertificates',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('RC_D', models.CharField(max_length=1, null=True)),
                ('RC_REC', models.IntegerField()),
                ('RC_UNIQUE', models.CharField(max_length=18)),
                ('RC_P_KEY', models.CharField(unique=True, max_length=6)),
                ('RC_VC_KEY', models.CharField(max_length=1)),
                ('RC_R_KEY', models.CharField(max_length=4)),
                ('RC_CG_KEY', models.CharField(max_length=4)),
                ('RC_Source', models.CharField(max_length=1)),
                ('RC_Interval', models.IntegerField()),
                ('RC_Time_Last', models.DateTimeField()),
                ('RC_Who_Last', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='SERVICE_RECORDS',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('S_D', models.CharField(max_length=1, null=True)),
                ('S_REC', models.IntegerField()),
                ('S_UNIQUE', models.CharField(max_length=13)),
                ('S_CON_UNIQUE', models.CharField(max_length=10)),
                ('S_ID_B_ID', models.CharField(max_length=4)),
                ('S_Start', models.DateTimeField()),
                ('S_End', models.DateTimeField()),
                ('S_Why', models.CharField(max_length=1)),
                ('S_Rank_R_KEY', models.CharField(max_length=4)),
                ('S_Vsl_V_KEY', models.CharField(max_length=4)),
                ('S_Vsl_Name', models.CharField(max_length=20)),
                ('S_Principal', models.CharField(max_length=20)),
                ('S_CN_KEY', models.CharField(max_length=2)),
                ('S_GRT', models.CharField(max_length=6)),
                ('S_Type_VT_KEY', models.CharField(max_length=4)),
                ('S_Engine', models.CharField(max_length=6)),
                ('S_HorsePower', models.CharField(max_length=8)),
                ('S_Time_Last', models.DateTimeField()),
                ('S_Who_Last', models.DateTimeField()),
            ],
        ),
    ]
