# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CERT_GROUPS',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('CG_D', models.CharField(max_length=1, null=True)),
                ('CG_KEY', models.CharField(max_length=4)),
                ('CG_Full', models.CharField(max_length=64)),
                ('CG_Time_Last', models.DateTimeField()),
                ('CG_Who_Last', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='COMPONENT_SCALES',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('CS_D', models.CharField(max_length=1, null=True)),
                ('CS_KEY', models.CharField(max_length=2)),
                ('CS_Full', models.CharField(max_length=40)),
                ('CS_Time_Last', models.DateTimeField()),
                ('CS_Who_Last', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('CO_D', models.CharField(max_length=1, null=True)),
                ('CO_KEY', models.CharField(max_length=4)),
                ('CO_Full', models.CharField(max_length=40)),
                ('CO_Full_GRK', models.CharField(max_length=40)),
                ('CO_CS_KEY', models.CharField(max_length=2)),
                ('CO_Sort', models.IntegerField()),
                ('CO_Table', models.CharField(max_length=1)),
                ('CO_Skip', models.CharField(max_length=1)),
                ('CO_Taxable', models.CharField(max_length=1)),
                ('CO_Who_Pays', models.CharField(max_length=1)),
                ('CO_Is_Tax', models.CharField(max_length=1)),
                ('CO_Prt_Monthly', models.CharField(max_length=1)),
                ('CO_Prt_Contract_GCA', models.CharField(max_length=1)),
                ('CO_Prt_Payroll', models.CharField(max_length=1)),
                ('CO_Prt_R_Payroll', models.CharField(max_length=1)),
                ('CO_Prt_Retro', models.CharField(max_length=1)),
                ('CO_Prt_Article', models.CharField(max_length=1)),
                ('CO_Prt_Clone', models.CharField(max_length=1)),
                ('CO_Prt_Quest3', models.CharField(max_length=1)),
                ('CO_Prt_Quest4', models.CharField(max_length=1)),
                ('CO_Prt_Quest5', models.CharField(max_length=1)),
                ('CO_Mon_Amnt', models.CharField(max_length=20)),
                ('CO_Tot_Amnt', models.CharField(max_length=20)),
                ('CO_Fld_Depend1', models.CharField(max_length=20)),
                ('CO_Fld_Depend2', models.CharField(max_length=20)),
                ('CO_Fld_Change1', models.CharField(max_length=20)),
                ('CO_Fld_Change2', models.CharField(max_length=20)),
                ('CO_Fld_Special', models.CharField(max_length=80)),
                ('CO_Time_Last', models.DateTimeField()),
                ('CO_Who_Last', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CONTRACTS',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('CON_D', models.CharField(max_length=1, null=True)),
                ('CON_Number', models.IntegerField()),
                ('CON_B_ID', models.CharField(max_length=4)),
                ('CON_W_CS_KEY', models.CharField(max_length=2)),
                ('CON_T_CS_KEY', models.CharField(max_length=2)),
                ('CON_MAN_KEY', models.CharField(max_length=4)),
                ('CON_Prin_P_KEY', models.CharField(max_length=6)),
                ('CON_Master_P_KEY', models.CharField(max_length=6)),
                ('CON_Wage_W_REC', models.CharField(max_length=8)),
                ('CON_Vsl_V_KEY', models.CharField(max_length=4)),
                ('CON_Rank_R_KEY', models.CharField(max_length=4)),
                ('CON_Crew_Category', models.CharField(max_length=1)),
                ('CON_Length', models.IntegerField()),
                ('CON_PDOS', models.DateTimeField()),
                ('CON_Money_Beg', models.DateTimeField()),
                ('CON_Embark', models.DateTimeField()),
                ('CON_Embark_Com', models.CharField(max_length=80)),
                ('CON_Join', models.DateTimeField()),
                ('CON_Join_Where', models.CharField(max_length=16)),
                ('CON_Left', models.DateTimeField()),
                ('CON_Left_Where', models.CharField(max_length=16)),
                ('CON_Disembark', models.DateTimeField()),
                ('CON_Disembark_Com', models.CharField(max_length=80)),
                ('CON_Money_End', models.DateTimeField()),
                ('CON_Reason_Signoff', models.CharField(max_length=20)),
                ('CON_Date_Fitness', models.DateTimeField()),
                ('CON_Contract_Date', models.DateTimeField()),
                ('CON_POEA_Date', models.DateTimeField()),
                ('CON_OEC', models.IntegerField()),
                ('CON_Last_Eval_Rcv', models.CharField(max_length=1)),
                ('CON_Seniority', models.IntegerField()),
                ('CON_Senior_Date', models.DateTimeField()),
                ('CON_Mth_Basic', models.DecimalField(max_digits=16, decimal_places=2)),
                ('CON_Mth_Extra1', models.DecimalField(max_digits=16, decimal_places=2)),
                ('CON_Mth_Extra1_Descr', models.CharField(max_length=32)),
                ('CON_Mth_Extra2', models.DecimalField(max_digits=16, decimal_places=2)),
                ('CON_Mth_Extra2_Descr', models.CharField(max_length=32)),
                ('CON_Fix_Mth_OT', models.DecimalField(max_digits=16, decimal_places=2)),
                ('CON_Hourly_OT_Rate', models.DecimalField(max_digits=16, decimal_places=2)),
                ('CON_Min_Mth_OT_Hours', models.IntegerField()),
                ('CON_Hours_week', models.IntegerField()),
                ('CON_Time_Last', models.DateTimeField()),
                ('CON_Who_Last', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='COUNTRY',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('CN_D', models.CharField(max_length=1, null=True)),
                ('CN_KEY', models.CharField(max_length=2)),
                ('CN_Full', models.CharField(max_length=45)),
                ('CN_Nationality', models.CharField(max_length=20)),
                ('CN_Time_Last', models.DateTimeField()),
                ('CN_Who_Last', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='MANNING_AGENT',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('MAN_D', models.CharField(max_length=1, null=True)),
                ('MAN_KEY', models.CharField(max_length=4)),
                ('MAN_Full', models.CharField(max_length=40)),
                ('MAN_Addr1', models.CharField(max_length=32)),
                ('MAN_Addr2', models.CharField(max_length=32)),
                ('MAN_Addr3', models.CharField(max_length=32)),
                ('MAN_Addr4', models.CharField(max_length=32)),
                ('MAN_LawCountry', models.CharField(max_length=32)),
                ('MAN_PhoneTelex', models.CharField(max_length=32)),
                ('MAN_W_Tax_Agnt', models.CharField(max_length=18)),
                ('MAN_TaxAccnt', models.CharField(max_length=20)),
                ('MAN_SSS', models.CharField(max_length=16)),
                ('MAN_AOH', models.CharField(max_length=32)),
                ('MAN_OF_KEY', models.CharField(max_length=4)),
                ('MAN_Time_Last', models.DateTimeField()),
                ('MAN_Who_Last', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OFFICIAL_SIGNERS',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('OF_D', models.CharField(max_length=1, null=True)),
                ('OF_KEY', models.CharField(max_length=4)),
                ('OF_Full', models.CharField(max_length=24)),
                ('OF_Position', models.CharField(max_length=16)),
                ('OF_TaxAcct', models.CharField(max_length=20)),
                ('OF_Time_Last', models.DateTimeField()),
                ('OF_Who_Last', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TAX_CATEGORIES',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('TC_D', models.CharField(max_length=1, null=True)),
                ('TC_KEY', models.CharField(max_length=1)),
                ('TC_Full', models.CharField(max_length=40)),
                ('TC_Time_Last', models.DateTimeField()),
                ('TC_Who_Last', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='VESSEL_CATEGORIES',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('VC_D', models.CharField(max_length=1, null=True)),
                ('VC_KEY', models.CharField(max_length=4)),
                ('VC_Full', models.CharField(max_length=26)),
                ('VC_Time_Last', models.DateTimeField()),
                ('VC_Who_Last', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VESSEL_TYPE',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('VT_D', models.CharField(max_length=1, null=True)),
                ('VT_KEY', models.CharField(max_length=4)),
                ('VT_Full', models.CharField(max_length=16)),
                ('VT_Time_Last', models.DateTimeField()),
                ('VT_Who_Last', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VESSELS',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('V_D', models.CharField(max_length=1, null=True)),
                ('V_KEY', models.CharField(max_length=4)),
                ('V_Type', models.CharField(max_length=4)),
                ('V_Full', models.CharField(max_length=32)),
                ('V_P_KEY', models.CharField(max_length=6)),
                ('V_Registry', models.CharField(max_length=12)),
                ('V_CN_KEY', models.CharField(max_length=2)),
                ('V_RegNumber', models.CharField(max_length=16)),
                ('V_GRT', models.IntegerField()),
                ('V_NRT', models.IntegerField()),
                ('V_DWT', models.CharField(max_length=8)),
                ('V_Engine', models.CharField(max_length=6)),
                ('V_HorsePower', models.CharField(max_length=8)),
                ('V_Class', models.CharField(max_length=4)),
                ('V_Yard', models.CharField(max_length=12)),
                ('V_YearBuilt', models.IntegerField()),
                ('V_Trades', models.CharField(max_length=16)),
                ('V_UMS', models.CharField(max_length=1)),
                ('V_CallSign', models.CharField(max_length=6)),
                ('V_Owner_Ship', models.CharField(max_length=45)),
                ('V_IMO', models.CharField(max_length=12)),
                ('V_Status', models.CharField(max_length=1)),
                ('V_End', models.DateTimeField()),
                ('V_Main_Cat', models.CharField(max_length=1)),
                ('V_Equip_1', models.CharField(max_length=1)),
                ('V_Equip_2', models.CharField(max_length=1)),
                ('V_Equip_3', models.CharField(max_length=1)),
                ('V_Equip_4', models.CharField(max_length=1)),
                ('V_TFS_Fleet', models.CharField(max_length=1)),
                ('V_TFS_Ship', models.CharField(max_length=4)),
                ('V_Email_1', models.CharField(max_length=28)),
                ('V_Email_2', models.CharField(max_length=28)),
                ('V_Time_Last', models.DateTimeField()),
                ('V_Who_Last', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WAGES',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('W_D', models.CharField(max_length=1, null=True)),
                ('W_P_KEY', models.CharField(max_length=6)),
                ('W_Date', models.DateTimeField()),
                ('W_Rank_R_KEY', models.CharField(max_length=4)),
                ('W_CS_KEY', models.CharField(max_length=2)),
                ('W_M_Money', models.CharField(max_length=3)),
                ('W_Mth_Basic', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Fix_Mth_OT', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Hourly_OT_Rate', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Min_Mth_OT_Hours', models.IntegerField()),
                ('W_Hours_Week', models.IntegerField()),
                ('W_Comp_Type_1', models.CharField(max_length=3)),
                ('W_Comp_Name_1', models.CharField(max_length=16)),
                ('W_Comp_Amnt_1', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Comp_Type_2', models.CharField(max_length=3)),
                ('W_Comp_Name_2', models.CharField(max_length=16)),
                ('W_Comp_Amnt_2', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Comp_Type_3', models.CharField(max_length=3)),
                ('W_Comp_Name_3', models.CharField(max_length=16)),
                ('W_Comp_Amnt_3', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Comp_Type_4', models.CharField(max_length=3)),
                ('W_Comp_Name_4', models.CharField(max_length=16)),
                ('W_Comp_Amnt_4', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Comp_Type_5', models.CharField(max_length=3)),
                ('W_Comp_Name_5', models.CharField(max_length=16)),
                ('W_Comp_Amnt_5', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Comp_Type_6', models.CharField(max_length=3)),
                ('W_Comp_Name_6', models.CharField(max_length=16)),
                ('W_Comp_Amnt_6', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Comp_Type_7', models.CharField(max_length=3)),
                ('W_Comp_Name_7', models.CharField(max_length=16)),
                ('W_Comp_Amnt_7', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Comp_Type_8', models.CharField(max_length=3)),
                ('W_Comp_Name_8', models.CharField(max_length=16)),
                ('W_Comp_Amnt_8', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Comp_Type_9', models.CharField(max_length=3)),
                ('W_Comp_Name_9', models.CharField(max_length=16)),
                ('W_Comp_Amnt_9', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Comp_Type_10', models.CharField(max_length=3)),
                ('W_Comp_Name_10', models.CharField(max_length=16)),
                ('W_Comp_Amnt_10', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Comp_Type_11', models.CharField(max_length=3)),
                ('W_Comp_Name_11', models.CharField(max_length=16)),
                ('W_Comp_Amnt_11', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Comp_Type_12', models.CharField(max_length=3)),
                ('W_Comp_Name_12', models.CharField(max_length=16)),
                ('W_Comp_Amnt_12', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Comp_Type_13', models.CharField(max_length=3)),
                ('W_Comp_Name_13', models.CharField(max_length=16)),
                ('W_Comp_Amnt_13', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Comp_Type_14', models.CharField(max_length=3)),
                ('W_Comp_Name_14', models.CharField(max_length=16)),
                ('W_Comp_Amnt_14', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Comp_Type_15', models.CharField(max_length=3)),
                ('W_Comp_Name_15', models.CharField(max_length=16)),
                ('W_Comp_Amnt_15', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Comp_Type_16', models.CharField(max_length=3)),
                ('W_Comp_Name_16', models.CharField(max_length=16)),
                ('W_Comp_Amnt_16', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Comp_Type_17', models.CharField(max_length=3)),
                ('W_Comp_Name_17', models.CharField(max_length=16)),
                ('W_Comp_Amnt_17', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Comp_Type_18', models.CharField(max_length=3)),
                ('W_Comp_Name_18', models.CharField(max_length=16)),
                ('W_Comp_Amnt_18', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Comp_Type_19', models.CharField(max_length=3)),
                ('W_Comp_Name_19', models.CharField(max_length=16)),
                ('W_Comp_Amnt_19', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Comp_Type_20', models.CharField(max_length=3)),
                ('W_Comp_Name_20', models.CharField(max_length=16)),
                ('W_Comp_Amnt_20', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Comp_Type_21', models.CharField(max_length=3)),
                ('W_Comp_Name_21', models.CharField(max_length=16)),
                ('W_Comp_Amnt_21', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Comp_Type_22', models.CharField(max_length=3)),
                ('W_Comp_Name_22', models.CharField(max_length=16)),
                ('W_Comp_Amnt_22', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Comp_Type_23', models.CharField(max_length=3)),
                ('W_Comp_Name_23', models.CharField(max_length=16)),
                ('W_Comp_Amnt_23', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Comp_Type_24', models.CharField(max_length=3)),
                ('W_Comp_Name_24', models.CharField(max_length=16)),
                ('W_Comp_Amnt_24', models.DecimalField(max_digits=16, decimal_places=2)),
                ('W_Sen_1', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_Sen_2', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_Sen_3', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_Sen_4', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_Sen_5', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_Sen_6', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_Sen_7', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_Sen_8', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_Sen_9', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_Sen_10', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_Sen_11', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_Sen_Rank_1', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_Sen_Rank_2', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_Sen_Rank_3', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_Sen_Rank_4', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_Sen_Rank_5', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_Sen_Rank_6', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_Sen_Rank_7', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_Sen_Rank_8', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_Sen_Rank_9', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_Sen_Rank_10', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_Sen_Rank_11', models.DecimalField(max_digits=8, decimal_places=2)),
                ('W_Time_Last', models.DateTimeField()),
                ('W_Who_Last', models.DateTimeField()),
            ],
        ),
    ]
